---
version: '3'
services:
  a2ml:
    build: .
    image: augerai/a2ml
    working_dir: /app
    command: pytest -vv -s -o log_cli=True -o log_cli_level=info -W ignore tests/test_celery_tasks/test_tasks.py::TestTasks::test_train_server
    env_file: 
      - develop.env
      - develop.client.env
    volumes:
      - .:/app
    depends_on:
      - a2ml-worker
      - a2ml-server

  a2ml-worker:
    build: .
    image: augerai/a2ml
    command: a2ml worker
    env_file: develop.env
    volumes:
      - .:/app
    depends_on:
      - minio
      - redis

  a2ml-server:
    build: .
    image: augerai/a2ml
    command: a2ml server
    env_file: develop.env
    volumes:
      - .:/app
    depends_on:
      - minio
      - redis
    ports:
      - 8000:8000

  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    command: server --compat /data
    ports:
      - 9000:9000
    volumes:
      - ./tmp/data/:/data/
    env_file: develop.env

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    command: redis-server --save "" --appendonly no

volumes:
  redis_data:
