---
version: '3'
services:
  server:
    build: .
    image: deeplearninc/a2ml
    command: a2ml server --loglevel=info
    env_file: develop.env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - minio
      - redis

  worker:
    build: .
    image: deeplearninc/a2ml
    command: a2ml worker --loglevel=info
    env_file: develop.env
    volumes:
      - .:/app
    depends_on:
      - minio
      - redis

  minio:
    image: minio/minio:RELEASE.2020-03-14T02-21-58Z
    command: server --compat /data
    ports:
      - 9000:9000
    volumes:
      - ./tmp/docker/data/:/data/
    env_file: develop.env

  redis:
    image: redis
    ports:
      - 6379
