---
version: '3'
services:
  a2ml:
    image: augerai/a2ml:latest
    command: python -m py.test tests
    env_file: develop.env
    depends_on:
      - createbucket
      - minio
      - redis

  minio:
    image: minio/minio:RELEASE.2020-03-14T02-21-58Z
    command: server --compat /data
    ports:
      - 9000:9000
    env_file: develop.env

  createbucket:
    build:
      context: .
      dockerfile: tests/minio_bootstrapper/Dockerfile
    image: minio-bootstrapper
    env_file: develop.env
    entrypoint: >
      /bin/sh -c "
      wget http://minio:9000/minio/health/ready;
      until /usr/bin/mc config host add myminio http://minio:9000 $${MINIO_ACCESS_KEY} $${MINIO_SECRET_KEY}; do sleep 0.5; done;
      /usr/bin/mc rm -r --force myminio/sample-bucket;
      /usr/bin/mc mb myminio/sample-bucket;
      /usr/bin/mc policy set upload myminio/sample-bucket;
      /usr/bin/mc cp /data/iris.csv myminio/sample-bucket/workspace/projects/a2ml-app/files/;
      /usr/bin/mc cp /data/iris_for_predict.csv myminio/sample-bucket/workspace/projects/a2ml-app/files/;
      "
    depends_on:
      - minio

  redis:
    image: redis
    ports:
      - 6379
