name: docs

on:
  push:
    branches: github_actions
    # tags:
    #   - v.*

jobs:
  build_publish_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          virtualenv venv
          source venv/bin/activate
          make develop-docs

      - name: Build docs
        run: |
          source venv/bin/activate
          cd docs/
          make html

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Deploy docs to gh-pages branch
        run: |
          npm install -g --silent gh-pages@2.2.0
          gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/build/html

# git config user.email "23641280+augerbot@users.noreply.github.com"
# git config user.name "augerbot"          