name: docs

on:
  push:
    branches: github_actions
    # tags:
    #   - v*

jobs:
  build_publish_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Build docs
        run: |
          make develop-docs
          cd docs/
          make html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
    
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 14

      # - name: Deploy docs to gh-pages branch
      #   run: |
      #     git config user.email "23641280+augerbot@users.noreply.github.com"
      #     git config user.name "augerbot"        
      #     npm install -g --silent gh-pages@2.2.0
      #     gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/build/html

          