name: test

on: 
  push:
    branches:
      - *
    tags-ignore:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: make config docker-test
     